export const TICK_BOARD = "TICK_BOARD";
export const GENERATE_TICK = "GENERATE_TICK";
export const SELECT_BOARD_SIZE = "SELECT_BOARD_SIZE";
export const GAME_WINNER_STATE = "GAME_WINNER_STATE";
export const GAME_DRAW_STATE = "GAME_DRAW_STATE";
export const GAME_PLAYER_CHANGE = "GAME_PLAYER_CHANGE";
